//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SHAIN
    {
        public string EmpID { get; set; }
        public string NameKJ1 { get; set; }
        public string NameKJ2 { get; set; }
        public string NameKN { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string EmployeeKbn { get; set; }
        public string BaseDate { get; set; }
        public Nullable<int> AdYear { get; set; }
        public Nullable<int> BaseAge { get; set; }
        public Nullable<int> AdCareerYear { get; set; }
        public Nullable<int> CareerYear { get; set; }
        public string Mail { get; set; }
        public string Station { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public Nullable<int> BreakNum { get; set; }
        public Nullable<int> DaysWorked { get; set; }
        public string College { get; set; }
        public string Department1 { get; set; }
        public string Department2 { get; set; }
        public string InsMark { get; set; }
        public string InsNum { get; set; }
        public string Job { get; set; }
        public string GroupID { get; set; }
        public string TraGroup { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
